name: spots
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  go_router: ^14.2.7
  riverpod_annotation: ^2.3.5
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firefuel: ^0.4.1
  flutter_gen: ^5.4.0
  flutter_svg: ^2.0.10+1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
  line_length: 80

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
