// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbHt2JqkppIIyrg7iknh2OKmV04640OTs',
    appId: '1:168746087000:web:b0dfd0e0f90301c5b8502d',
    messagingSenderId: '168746087000',
    projectId: 'spots-782df',
    authDomain: 'spots-782df.firebaseapp.com',
    storageBucket: 'spots-782df.appspot.com',
    measurementId: 'G-L6W8Y40EZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBB9QmKD4Ol7XQprMCNScCGYKWXSLx11Y',
    appId: '1:168746087000:android:46c5a75e707e9746b8502d',
    messagingSenderId: '168746087000',
    projectId: 'spots-782df',
    storageBucket: 'spots-782df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl_kL9chjzFHB45LZOyT0yb6_ePlMvXAQ',
    appId: '1:168746087000:ios:73ab72450001f366b8502d',
    messagingSenderId: '168746087000',
    projectId: 'spots-782df',
    storageBucket: 'spots-782df.appspot.com',
    iosBundleId: 'com.example.Spots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl_kL9chjzFHB45LZOyT0yb6_ePlMvXAQ',
    appId: '1:168746087000:ios:dfb398038c99053cb8502d',
    messagingSenderId: '168746087000',
    projectId: 'spots-782df',
    storageBucket: 'spots-782df.appspot.com',
    iosBundleId: 'com.example.Spots.RunnerTests',
  );
}
